version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: galleryapp_db
    restart: always
    environment:
      POSTGRES_USER: gallery_user
      POSTGRES_PASSWORD: gallery_pass
      POSTGRES_DB: galleryapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
